In [7]:
import pandas as pd

In [8]:
file="college-salaries/mergedNew.csv"

In [9]:
df=pd.read_csv(file)
list(df)

['Unnamed: 0',
 'UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'ACCREDAGENCY',
 'INSTURL',
 'NPCURL',
 'LATITUDE',
 'LONGITUDE',
 'Carnegie Basic Class.',
 'Carnegie Undergrad. Prof.',
 'Carengies Size Set.',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'ADM_RATE_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'UGDS',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 '% Part-Time Undergrad',
 'Currently Operating',
 'TUITIONFEE_IN State',
 'TUITIONFEE_OUT State',
 'Paid Tuition per Full time student',
 'Expenditure per full time student',
 'Average Faculty Salary',
 'Percent Fulltime Faculty',
 'Percent Pell',
 'Percent Federal Loan',
 'Percent Above 25 Years Old',
 'Credit Default Rate 3 Years',
 'All Students Median Debt',
 'Graduate Median Debt',
 'Percent Undergrad Men',
 'Percent Undergrad Women',
 'Title 4 Date',
 'D_PCTPELL_PCTFLOAN',
 'OPENADMP',
 'ACCREDCODE',
 'Rank\xa0\xa0',
 'School Name',
 'School Type\xa0',
 'Early Career Pay\xa0',
 'Mid-Career Pay\xa0',
 '% High Meaning\xa0',
 '% STEM Degrees\xa0']

In [10]:
df_merge1=df.drop(["Unnamed: 0", "School Name", "ACCREDCODE", "OPENADMP", "NPCURL", "INSTURL", "ACCREDAGENCY", "Currently Operating"], axis=1)
df_merge1.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,LATITUDE,LONGITUDE,Carnegie Basic Class.,...,Percent Undergrad Men,Percent Undergrad Women,Title 4 Date,D_PCTPELL_PCTFLOAN,Rank,School Type,Early Career Pay,Mid-Career Pay,% High Meaning,% STEM Degrees
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,34.783368,-86.568502,18.0,...,0.4617,0.5383,1965-12-12 00:00:00,4210.0,1026 (tie),"For Sports Fans, State School",46200,75100,0.59,0.19
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,33.502230,-86.809170,15.0,...,0.4116,0.5884,1965-12-01 00:00:00,11679.0,733 (tie),"Research University, For Sports Fans, State Sc...",46000,81800,0.60,0.17
2,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,34.722818,-86.638420,15.0,...,0.5740,0.4260,1965-12-01 00:00:00,5618.0,240 (tie),"Research University, State School",54200,98500,0.59,0.42
3,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,32.364317,-86.295677,18.0,...,0.3850,0.6150,1965-12-01 00:00:00,4805.0,1274 (tie),"For Sports Fans, State School",38300,68500,0.62,0.14
4,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,33.214400,-87.545766,16.0,...,0.4525,0.5475,1965-12-01 00:00:00,30752.0,407 (tie),"Party School, Research University, For Sports ...",49000,90900,0.51,0.15

In [11]:
df_merge2=df_merge1.rename(columns={'Rank\xa0\xa0':"Rank", 'School Type\xa0':"School Type", 'Early Career Pay\xa0':"Early Career", 'Mid-Career Pay\xa0':"Mid-Career Pay", '% High Meaning\xa0':"% High Meaning", '% STEM Degrees\xa0':"% STEM Degrees"})
list(df_merge2)

['UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'LATITUDE',
 'LONGITUDE',
 'Carnegie Basic Class.',
 'Carnegie Undergrad. Prof.',
 'Carengies Size Set.',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'ADM_RATE_ALL',
 'PCIP01',
 'PCIP03',
 'PCIP04',
 'PCIP05',
 'PCIP09',
 'PCIP10',
 'PCIP11',
 'PCIP12',
 'PCIP13',
 'PCIP14',
 'PCIP15',
 'PCIP16',
 'PCIP19',
 'PCIP22',
 'PCIP23',
 'PCIP24',
 'PCIP25',
 'PCIP26',
 'PCIP27',
 'PCIP29',
 'PCIP30',
 'PCIP31',
 'PCIP38',
 'PCIP39',
 'PCIP40',
 'PCIP41',
 'PCIP42',
 'PCIP43',
 'PCIP44',
 'PCIP45',
 'PCIP46',
 'PCIP47',
 'PCIP48',
 'PCIP49',
 'PCIP50',
 'PCIP51',
 'PCIP52',
 'PCIP54',
 'UGDS',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 '% Part-Time Undergrad',
 'TUITIONFEE_IN State',
 'TUITIONFEE_OUT State',
 'Paid Tuition per Full time student',
 'Expenditure per full time student',
 'Average Faculty Salary',
 'Percent Fulltime Faculty',
 'Percent Pell',
 'Percent Federal Loan',
 'Percent Above 25 Years Old',
 'Credit Default Rate 3 Years',
 'All Students Median Debt',
 'Graduate Median Debt',
 'Percent Undergrad Men',
 'Percent Undergrad Women',
 'Title 4 Date',
 'D_PCTPELL_PCTFLOAN',
 'Rank',
 'School Type',
 'Early Career',
 'Mid-Career Pay',
 '% High Meaning',
 '% STEM Degrees']

In [12]:
df_merge2[df_merge2["Carengies Size Set."]!=5]
df_merge2[df_merge2["Carengies Size Set."]!= -2]
df_merge2[df_merge2["Carengies Size Set."]!=1]
df_merge2.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,LATITUDE,LONGITUDE,Carnegie Basic Class.,...,Percent Undergrad Men,Percent Undergrad Women,Title 4 Date,D_PCTPELL_PCTFLOAN,Rank,School Type,Early Career,Mid-Career Pay,% High Meaning,% STEM Degrees
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,34.783368,-86.568502,18.0,...,0.4617,0.5383,1965-12-12 00:00:00,4210.0,1026 (tie),"For Sports Fans, State School",46200,75100,0.59,0.19
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,33.502230,-86.809170,15.0,...,0.4116,0.5884,1965-12-01 00:00:00,11679.0,733 (tie),"Research University, For Sports Fans, State Sc...",46000,81800,0.60,0.17
2,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,34.722818,-86.638420,15.0,...,0.5740,0.4260,1965-12-01 00:00:00,5618.0,240 (tie),"Research University, State School",54200,98500,0.59,0.42
3,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,32.364317,-86.295677,18.0,...,0.3850,0.6150,1965-12-01 00:00:00,4805.0,1274 (tie),"For Sports Fans, State School",38300,68500,0.62,0.14
4,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,33.214400,-87.545766,16.0,...,0.4525,0.5475,1965-12-01 00:00:00,30752.0,407 (tie),"Party School, Research University, For Sports ...",49000,90900,0.51,0.15

In [13]:
df_merge3=df_merge2.rename(columns= {"PCIP01": "Agriculture", "PCIP03": "Natural Resources and Conservation", "PCIP04":"Architecture", 
"PCIP05": "Ethnic, Culture and Gender Studies", 
"PCIP09": "Communication and Journalism",
"PCIP10": "Communications Technologies/Technicians and Support Services",
"PCIP11": "Computer and Information Sciences and Support Services",
"PCIP13": "Education", "PCIP12":"Personal and Culinary Services",                                    
"PCIP14": "Engineering",
"PCIP15": "Engineering Technologies and Engineering-Related Fields",
"PCIP16": "Foreign Languages, Literatures and Linguistics",
"PCIP19": "Family and Consumer Sciences/Human Sciences",
"PCIP22": "Legal Professions and Studies",
"PCIP23": "English Language and Literature/Letters",
"PCIP24": "Liberal Arts and Sciences, General Studies and Humanities",
"PCIP25": "Library Science",
"PCIP26": "Biological and Biomedical Studies",
"PCIP27": "Mathematics and Statistics",
"PCIP29": "Military Technologies and Applied Sciences",
"PCIP30": "Multi/Interdisciplinary Studies",
"PCIP31": "Parks, Recreation, Leisure, and Fitness Studies",
"PCIP38": "Philosophy and Religious Studies",
"PCIP39": "Theology and Religious Vocations",
"PCIP40": "Physical Sciences",
"PCIP41": "Science Technologies/Technicians",
"PCIP42": "Psychology",
"PCIP43": "Homeland Security, Law Enforcement and Firefighting",
"PCIP44": "Public Administration and Social Service Professions",
"PCIP45": "Social Sciences",
"PCIP46": "Construction Trades",
"PCIP47": "Mechanic and Repair Technologies/Technicians",
"PCIP48": "Precision Production",
"PCIP49": "Transportation/Materials Moving",
"PCIP50": "Visual/Performing Arts",
"PCIP51": "Health Professions",
"PCIP52": "Business, Management, and Marketing",
"PCIP54":"History"})

In [14]:
list(df_merge3)

['UNITID',
 'OPEID',
 'OPEID6',
 'INSTNM',
 'CITY',
 'STABBR',
 'ZIP',
 'LATITUDE',
 'LONGITUDE',
 'Carnegie Basic Class.',
 'Carnegie Undergrad. Prof.',
 'Carengies Size Set.',
 'HBCU',
 'PBI',
 'ANNHI',
 'TRIBAL',
 'AANAPII',
 'HSI',
 'NANTI',
 'MENONLY',
 'WOMENONLY',
 'ADM_RATE_ALL',
 'Agriculture',
 'Natural Resources and Conservation',
 'Architecture',
 'Ethnic, Culture and Gender Studies',
 'Communication and Journalism',
 'Communications Technologies/Technicians and Support Services',
 'Computer and Information Sciences and Support Services',
 'Personal and Culinary Services',
 'Education',
 'Engineering',
 'Engineering Technologies and Engineering-Related Fields',
 'Foreign Languages, Literatures and Linguistics',
 'Family and Consumer Sciences/Human Sciences',
 'Legal Professions and Studies',
 'English Language and Literature/Letters',
 'Liberal Arts and Sciences, General Studies and Humanities',
 'Library Science',
 'Biological and Biomedical Studies',
 'Mathematics and Statistics',
 'Military Technologies and Applied Sciences',
 'Multi/Interdisciplinary Studies',
 'Parks, Recreation, Leisure, and Fitness Studies',
 'Philosophy and Religious Studies',
 'Theology and Religious Vocations',
 'Physical Sciences',
 'Science Technologies/Technicians',
 'Psychology',
 'Homeland Security, Law Enforcement and Firefighting',
 'Public Administration and Social Service Professions',
 'Social Sciences',
 'Construction Trades',
 'Mechanic and Repair Technologies/Technicians',
 'Precision Production',
 'Transportation/Materials Moving',
 'Visual/Performing Arts',
 'Health Professions',
 'Business, Management, and Marketing',
 'History',
 'UGDS',
 'UGDS_WHITE',
 'UGDS_BLACK',
 'UGDS_HISP',
 'UGDS_ASIAN',
 'UGDS_AIAN',
 'UGDS_NHPI',
 'UGDS_2MOR',
 'UGDS_NRA',
 'UGDS_UNKN',
 '% Part-Time Undergrad',
 'TUITIONFEE_IN State',
 'TUITIONFEE_OUT State',
 'Paid Tuition per Full time student',
 'Expenditure per full time student',
 'Average Faculty Salary',
 'Percent Fulltime Faculty',
 'Percent Pell',
 'Percent Federal Loan',
 'Percent Above 25 Years Old',
 'Credit Default Rate 3 Years',
 'All Students Median Debt',
 'Graduate Median Debt',
 'Percent Undergrad Men',
 'Percent Undergrad Women',
 'Title 4 Date',
 'D_PCTPELL_PCTFLOAN',
 'Rank',
 'School Type',
 'Early Career',
 'Mid-Career Pay',
 '% High Meaning',
 '% STEM Degrees']

In [15]:
df_merge3.to_csv("college-salaries/clean_data.csv")